# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Bicep

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Microsoft Azure Sponsorship (0b9c4dfd-d9ca-477a-b279-897de40f2d08)'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment sub create --location westus --template-file ./bicep/main.bicep 
      --parameters ./bicep/parameters.prod.json
